Finally statements are no longer rewritten to a sequence if no Exception was thrown

Finally statements have been allowed to rewrite to sequences when no Exception was throwable from within the try body.
This has been shown to be problematic as cleanup when an Error is thrown does not occur.

By default this has been reverted back to the pre-2018 behavior of not doing the rewrite.

To change this use the new switch `-checkactionfinally=off` to reenable the previous behavior.

This behavior can be observed by running the following code:

```d
import core.stdc.stdio;

void main() {
    try {
        callMe();
    } finally {
        printf("exiting!\n");
    }
}

void callMe() {
    throw new Error("hi there :)");
}
```

When the switch is set to `on`, "exiting!" will be printed.

The `-betterC` switch is unaffected by this change.
